[package]
name = "paclib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1"
regex = "1.3"
lazy_static = "1.4"
duktape = { path = "../duktape" }
duktape-sys = { path = "../duktape-sys" }
