[package]
name = "detox_net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2"
socket2 = "0.5"
thiserror = "1.0"
tokio = "1"

[lib]
doctest = false
