[package]
name = "dnsdetox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1", features = ["env"] }
dirs = "5.0"
dns-parser = "0.8"
env_logger = "0.10"
futures-util = { version = "0.3", default-features = false }
http = "1.0"
hyper = { version = "0.14", features = ["http1", "http2", "client", "stream", "tcp"] }
hyper-rustls = "0.24"
log = "0.4"
paclib = { path = "../paclib" }
proxy_client = { path = "../proxy_client" }
rustls = "0.21"
rustls-native-certs = "0.6"
thiserror = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros", "sync", "signal"] }
tokio-rustls =  "0.24"

[lib]
doctest = false
