[package]
name = "toml_get"
version = "0.6.0"
edition = "2024"
publish = false

[[bin]]
name = "toml_get"
path = "toml_get.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
toml = "0.9"
